# Generated by Django 3.2.18 on 2023-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_event_event_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_location_id',
        ),
    ]
