# Generated by Django 3.2.18 on 2023-04-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_remove_event_event_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('order_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
    ]
