# Generated by Django 3.2.18 on 2023-04-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0004_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event_id',
            new_name='eventid',
        ),
    ]
