# Generated by Django 3.2.18 on 2023-04-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0005_rename_event_id_participant_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eventid',
            field=models.CharField(max_length=255),
        ),
    ]
