# Generated by Django 3.2.18 on 2023-04-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0009_participant_qr_scanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='qr_scanned',
        ),
        migrations.AddField(
            model_name='participant',
            name='ticketcount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='tickettype',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('tickettype', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=100)),
                ('ticketprice', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.event')),
            ],
        ),
    ]
