# Generated by Django 3.2.18 on 2023-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0010_auto_20230411_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='ticketprice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='tickettype',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
