# Generated by Django 3.2.18 on 2023-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0011_auto_20230411_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketlimit',
            field=models.IntegerField(default=0),
        ),
    ]
