# Generated by Django 3.2.18 on 2023-04-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0012_event_ticketlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticketlimit',
        ),
        migrations.AddField(
            model_name='event',
            name='maxtickets',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ticketid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demo1.tickettype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_sabevent',
            field=models.BooleanField(default=None),
        ),
    ]
