# Generated by Django 3.2.18 on 2023-04-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0017_alter_participant_ticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='ticketid',
        ),
    ]
