# Generated by Django 3.2.18 on 2023-04-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0018_remove_participant_ticketid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tickettype',
        ),
    ]
