# Generated by Django 3.2.18 on 2023-04-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0020_auto_20230412_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='ticketid',
        ),
    ]
