# Generated by Django 3.2.18 on 2023-04-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0022_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_locations',
            name='location_link',
            field=models.URLField(default='http://google.map.com'),
        ),
    ]
