# Generated by Django 3.2.18 on 2023-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0023_event_locations_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
