# Generated by Django 3.2.18 on 2023-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0024_participant_qr_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qrimage',
            field=models.ImageField(default=False, upload_to='app/'),
        ),
    ]
