# Generated by Django 3.2.18 on 2023-04-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0026_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
