# Generated by Django 3.2.18 on 2023-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0028_participant_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='file',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
