# Generated by Django 3.2.18 on 2023-04-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0030_alter_participant_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='ticketcount',
        ),
    ]
