# Generated by Django 3.2.18 on 2023-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0031_remove_participant_ticketcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eventname',
            field=models.CharField(default='No Name', max_length=255),
        ),
    ]
