# Generated by Django 2.0.2 on 2023-04-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0034_ticketremain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticketremain',
        ),
    ]
