# Generated by Django 2.0.2 on 2023-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0035_delete_ticketremain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='profile',
            field=models.ImageField(default='app/event.jpg', upload_to='app/'),
        ),
    ]
